Feat: Update management-domains Federated Catalog documentation.
eclipse-tractusx/tractusx-edc pull request #1530
Opened 2024-09-03 11:13 UTC by bmg13

## WHAT

Suggestion update for Federated Catalog usage documentation.

## WHY

To keep Federated Catalog documentation up-to-date.

## FURTHER NOTES

Still in draft since is part of a larger Federated Catalog changes that are still to be aligned.

Closes

2024-09-11 06:16 UTC, paullatzelsperger requested changes

2024-09-11 06:16 UTC, paullatzelsperger commented on docs/development/management-domains/README.md
> +### Deployment Topologies
I don't think there is much value in copy-pasting documentation content that is already present in the upstream repo, especially picture material which might be copyrighted. 

Instead, I would document how to set up a catalog server, i.e. which assets must be added there, how the resulting federated catalog looks like (flattened vs hierarchical), etc.

2024-10-23 15:45 UTC, bmg13 commented
@jimmarino @paullatzelsperger @ndr-brt can this PR be reopened, please?

2024-12-09 11:22 UTC, bmg13 commented
@jimmarino @paullatzelsperger @ndr-brt can this PR be reopened, please?

2024-12-12 07:19 UTC, paullatzelsperger requested changes
To me, the text is quite misleading and IMO does not explain key concepts sufficiently. 

I would have expected to see at least the following aspects mentioned:
- the purpose of a catalog server, and what data structures it exposes (i.e. root catalog)
- how to set up a catalog server, i.e. that each sub-catalog is referenced via a `CatalogAsset` and how such a `CatalogAsset` looks like. This is crucial and should be accompanied by an example. For reference, you can look at [this example](https://github.com/eclipse-edc/MinimumViableDataspace/?tab=readme-ov-file#31-participants).
- the fact that querying of a catalog server is no different from querying a "normal" catalog endpoint, and what the response looks like
- the fact that contract negotiations etc. do still have to take place with the data-owning connector, not the catalog server
- the fact that the catalog server **doesn't actually** create a consolidated catalog, i.e. it does not pull back any data, it merely references other connectors' catalog endpoints
- the fact that the crawler lives on the consumer side 
- the purpose of a crawler and the fact, that it is the crawler that recursively traverses down a nested catalog 
- client-side caching: the crawler pulls back catalogs, stores them in the client-side cache (SQL), which is what the Query API uses


If I'm honest, I'm not 100% convinced that the concept of management domains and federated catalogs has been fully understood yet.

2024-12-12 07:19 UTC, paullatzelsperger commented on docs/development/management-domains/README.md
> +are available in a particular dataspace. Like so, after the Federated Catalog Crawler retrieves all catalogs, an aggregation of all is made and one single root catalog is exposed, similar to a Catalo
No, the crawler does **not** expose anything, least of all a root catalog.

2024-12-17 12:24 UTC, rafaelmag110 commented
@bmg13 
Given the latest review from Paul, I'd suggest you to consider his points and start again from a fresh slate. I'd close this PR, spend some time understanding the concepts that are missing and then I'd get back with a new one.

2024-12-17 14:26 UTC, bmg13 commented
> @bmg13 Given the latest review from Paul, I'd suggest you to consider his points and start again from a fresh slate. I'd close this PR, spend some time understanding the concepts that are missing and then I'd get back with a new one.

Following this feedback will close this pr and revisit in the future if opportunity arises.

2024-12-17 14:26 UTC, closed without merging