Fix: dataplaneId null for older TransferProcesses
eclipse-tractusx/tractusx-edc pull request #1534
Opened 2024-09-05 12:13 UTC by bmg13

## WHAT

Add a fix related with the null dataplaneId value in a TrasnferProcess.

## WHY

To avoid terminated null dp_id's errors. Similar to https://github.com/eclipse-edc/Connector/pull/4420

## FURTHER NOTES
Please check https://github.com/eclipse-edc/Connector/issues/4418 for more context

Closes TBD

2024-09-09 15:24 UTC, bmg13 commented
@paullatzelsperger @wolf4ood can you please review? 🙇

2024-09-09 16:10 UTC, wolf4ood requested changes
The porting looks good, but i think the `DataPlaneSignalingFlowControllerTest` is missing

2024-09-10 04:51 UTC, paullatzelsperger commented
@wolf4ood reviewed, so I'm taking my own review off

2024-09-10 08:10 UTC, bmg13 commented
> The porting looks good, but i think the `DataPlaneSignalingFlowControllerTest` is missing

you're, right, thank you, added in https://github.com/eclipse-tractusx/tractusx-edc/pull/1534/commits/c86698ae5769b5fe4c00a908df3a248cb0375ab8

2024-09-10 08:33 UTC, bmg13 commented
Can you please re-run the tests here? everything is passing locally

2024-09-10 09:58 UTC, wolf4ood commented
@bmg13 i think we also have to port the test when the data plane is null when terminating

https://github.com/eclipse-edc/Connector/pull/4420/files#diff-18c8693725dbf0962879c1552c8e5e24c31af6190dd0a0e1d3d9200b9e250409R314

2024-09-10 16:52 UTC, bmg13 commented
> @bmg13 i think we also have to port the test when the data plane is null when terminating/suspending
> 
> https://github.com/eclipse-edc/Connector/pull/4420/files#diff-18c8693725dbf0962879c1552c8e5e24c31af6190dd0a0e1d3d9200b9e250409R314
> 
> https://github.com/eclipse-edc/Connector/pull/4420/files#diff-18c8693725dbf0962879c1552c8e5e24c31af6190dd0a0e1d3d9200b9e250409R262

The termination one was added in a later commit: https://github.com/eclipse-tractusx/tractusx-edc/pull/1534/commits/60ebfe166284d4f05ef939b09c2f1f4ff3861c40
the suspend I did not add since these changes added were only to termination and not to suspension

2024-09-11 08:19 UTC, wolf4ood approved these changes

2024-09-11 08:20 UTC, merged