fix: Adapt Helm Chart for version 0.3.x
eclipse-tractusx/tractusx-edc pull request #211
Opened 2023-04-13 08:16 UTC by tuncaytunc-zf

WHAT
Fixes some Helm Chart issues reported in #167 

WHY
The Helm Chart was not compatible with the version 0.3.x

2023-04-13 17:58 UTC, paullatzelsperger requested changes
`edc.api.observability` should be removed, as it is replaced by "our" observability API

2023-04-13 17:58 UTC, paullatzelsperger commented on edc-dataplane/edc-dataplane-base/build.gradle.kts
> +    runtimeOnly(project(":edc-extensions:observability-api-customization"))
our custom extension is a drop-in replacement, so `implementation(edc.api.observability)` (couple of lines above) should be deleted. And while you're there: could you replace all `implementation` dependencies with `runtimeOnly` dependencies?

also: nit - project-dependencies should be the first in the list.

2023-04-14 08:04 UTC, paullatzelsperger approved these changes

2023-04-14 11:36 UTC, ndr-brt approved these changes

2023-04-14 13:04 UTC, merged