feature: add explicit docker image creation during release process
eclipse-tractusx/tractusx-edc pull request #251
Opened 2023-04-19 19:16 UTC by paullatzelsperger

## WHAT

This PR adds a step to the `publish-new-release.yaml` workflow, that explicitly builds and pushes all Docker images with the release version as Docker tag.

For example, if we'd just released version `0.6.9`, it would create `edc-runtime-memory:0.6.9`, etc.

## WHY

Due to a security restriction, workflow runs that use GITHUB_TOKEN cannot trigger other workflows. 
Here, this is relevant because the `publish-new-release.yaml` flow creates a tag, which would normally trigger another `build.yaml` flow. Since we're using `GITHUB_TOKEN`s instead of PATs this doesn't happen.

## FURTHER NOTES

I also simplified the use of `matrix` builds in the other flows, effectively reducing the number of jobs that are launched.

Closes #250

2023-04-19 19:30 UTC, paullatzelsperger commented
markdown lint errors will be fixed once #252 is merged

2023-04-20 06:45 UTC, wolf4ood requested changes
Just a nit

2023-04-20 06:45 UTC, wolf4ood commented on .github/workflows/publish-docker.yaml
>      name: "Create Docker Images for the ControlPlane"
```suggestion
    name: "Create Docker Images"
```

2023-04-20 12:23 UTC, wolf4ood approved these changes

2023-04-21 06:54 UTC, merged