docs: Adapt "Local TXDC Setup.md" documentation
eclipse-tractusx/tractusx-edc pull request #297
Opened 2023-04-28 11:36 UTC by tuncaytunc-zf

## WHAT

Adapt the local TXDC setup documentation. 

## WHY

Some values in the local TXDC setup document were outdated. 

## FURTHER NOTES

Closes #286

2023-04-28 11:56 UTC, stephanbcbauer approved these changes
LGTM

2023-04-28 16:53 UTC, paullatzelsperger requested changes

2023-04-28 16:53 UTC, paullatzelsperger commented on docs/samples/Local TXDC Setup.md
> +    --set controlplane.image.tag=latest \
using `latest` is dangerous, because the `latest` tag gets overwritten on every build we do on tractusx-edc

2023-04-28 16:53 UTC, paullatzelsperger commented on docs/samples/Local TXDC Setup.md
> +    --set controlplane.image.tag=latest \
using `latest` is dangerous, because the `latest` tag gets overwritten on every build we do on tractusx-edc

2023-05-01 23:31 UTC, sekikn commented on docs/development/Run-business-tests-local.md
>  ```shel
Should we fix the format type as "sh" or "shell"?

2023-05-01 23:33 UTC, sekikn commented on docs/samples/Local TXDC Setup.md
> +the [Supporting Infrastructure](../../edc-tests/cucumber/src/main/resources/deployment/helm/supporting-infrastructure/README.md)
Just like this fix, should we also insert "cucumber" into the following two paths?

2023-05-01 23:36 UTC, sekikn commented on docs/samples/Local TXDC Setup.md
> +    --set controlplane.image.tag=latest \
I tried the fixed command, but ran into the following error unfortunately.

```
Error: INSTALLATION FAILED: execution error at (tractusx-connector/templates/deployment-controlplane.yaml:191:54): .Values.postgresql.username is required
```

Considering the context that PostgreSQL is disabled in the preceding infrastructure setup, how about adding the following option?

```
--set controlplane.image.repository=edc-controlplane-memory-hashicorp-vault
```

In addition, even if specifying the option above, `postgresql.username`, `postgresql.password`, and `postgresql.jdbcUrl` still seem to be required, though any value is OK for them. According to the document, [there is a `postgresql.enabled` option](https://github.com/eclipse-tractusx/tractusx-edc/blob/57da0cb124a3efea54d7fe5059d2b33b816167bf/charts/tractusx-connector/README.md?plain=1#L216), but it doesn't seem to be used in any Helm chart.

```
$ git grep postgresql.enabled
.github/workflows/business-tests.yaml:              --set postgresql.enabled=true \
.github/workflows/business-tests.yaml:              --set postgresql.enabled=true \
charts/tractusx-connector-app/README.md:| runtime.postgresql.enabled | bool | `false` |  |
charts/tractusx-connector/README.md:| postgresql.enabled | bool | `false` |  |
docs/development/Run-business-tests-local.md:  --set postgresql.enabled=true \
docs/development/Run-business-tests-local.md:  --set postgresql.enabled=true \
```

Is this a documentation bug, and if so, should we fix it in this PR?

2023-05-16 13:07 UTC, closed without merging