bug: Add migration for transferprocess_properties default value
eclipse-tractusx/tractusx-edc pull request #313
Opened 2023-05-04 13:13 UTC by bcronin90

## WHAT

Add default value for transferprocess-properties to SQL migration.

## WHY

See Issue #296. Changing Transferprocess.getProperties is out of scope for this repository, so the other approach was taken.

Closes #296

2023-05-05 04:19 UTC, florianrusch-zf commented on edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/transferprocess/V0_0_6__Snapshot_20230109_Update.sql
> +ALTER TABLE edc_transfer_process ADD CONSTRAINT transferprocess_properties DEFAULT "{}";
Missing empty line at EOF
```suggestion
ALTER TABLE edc_transfer_process ADD CONSTRAINT transferprocess_properties DEFAULT "{}";

```

2023-05-12 05:36 UTC, florianrusch-zf commented
@bcronin90 could you change the PR title prefix to `fix`? `bug` is not one of the suggestions in our [`pr_etiquette.md`](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/pr_etiquette.md)

And additionally, you changed an existing migration - wouldn't that mean, that if I upgrade my already existing EDC, that this migration would not been executed, because this migration was already been executed in the past? Don't we need a new migration?

2023-05-12 05:43 UTC, bcronin90 commented
> @bcronin90 could you change the PR title prefix to `fix`? `bug` is not one of the suggestions in our [`pr_etiquette.md`](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/pr_etiquette.md)
> 
> And additionally, you changed an existing migration - wouldn't that mean, that if I upgrade my already existing EDC, that this migration would not been executed, because this migration was already been executed in the past? Don't we need a new migration?

Changed the title. Yes, currently this would require re-running the migration. I can switch it to a new migration, but I have one issue that I'm not sure how to resolve then: Since the changes happen at the same version, how do I make sure the migrations are executed in the correct order, for a user who hasn't run it yet. Since Line 18 needs to be run after line 16.

2023-05-12 05:46 UTC, florianrusch-zf commented
Can't we simply create a new `v0.0.7....` migration. This will been executed automatically after the existing ones. Or not? 😅

2023-05-12 05:48 UTC, bcronin90 commented
> Can't we simply create a new `V0.0.7....` migration file? This will been executed automatically after the existing ones. Or not? sweat_smile

I was unaware our versioning allowed for that. On it!

2023-05-12 05:59 UTC, florianrusch-zf commented on edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/transferprocess/V0_0_7__Default_Value_For_Properties.sql
> +--
Please fix the copyright ;-)

2023-05-12 06:44 UTC, florianrusch-zf approved these changes

2023-05-16 13:08 UTC, paullatzelsperger commented
trying this out in a local postgres quickly shows that the migration should actually be: 
```sql
ALTER TABLE edc_transfer_process ALTER COLUMN transferprocess_properties SET DEFAULT '{}';
```

2023-05-16 13:09 UTC, florianrusch-zf commented
> did no-one try this out locally?

Nope, I trusted our pipelines & @bcronin90

2023-05-16 13:10 UTC, florianrusch-zf requested changes

2023-05-16 13:10 UTC, florianrusch-zf commented on edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/transferprocess/V0_0_7__Default_Value_For_Properties.sql
> +ALTER TABLE edc_transfer_process ADD CONSTRAINT transferprocess_properties DEFAULT "{}";
```suggestion
ALTER TABLE edc_transfer_process ALTER COLUMN transferprocess_properties SET DEFAULT '{}';
```

2023-05-16 13:39 UTC, bcronin90 commented
I'm in an internal thing today. Will get back to you tomorrow. ---- On Di, 16 Mai 2023 15:08:33 +0200  ***@***.***  wrote ----
trying this out in a local postgres quickly shows that the migration should actually be:
ALTER TABLE edc_transfer_process ALTER COLUMN transferprocess_properties SET DEFAULT '{}';


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-05-16 13:45 UTC, bcronin90 commented
Thanks for the suggestion. Should be correct, but I can't look at this today. Will check tomorrow ---- On Di, 16 Mai 2023 15:10:58 +0200  ***@***.***  wrote ----
@florianrusch-zf requested changes on this pull request.



In edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/transferprocess/V0_0_7__Default_Value_For_Properties.sql:
> @@ -0,0 +1,15 @@
+--
+--  Copyright (c) 2022 Mercedes-Benz Tech Innovation GmbH
+--
+--  This program and the accompanying materials are made available under the
+--  terms of the Apache License, Version 2.0 which is available at
+--  https://www.apache.org/licenses/LICENSE-2.0
+--
+--  SPDX-License-Identifier: Apache-2.0
+--
+--  Contributors:
+--       Mercedes-Benz Tech Innovation GmbH - Rewrite to be SQL Init Schema
+--
+
+-- set default value
+ALTER TABLE edc_transfer_process ADD CONSTRAINT transferprocess_properties DEFAULT "{}";

⬇️ Suggested change
-ALTER TABLE edc_transfer_process ADD CONSTRAINT transferprocess_properties DEFAULT "{}";
+ALTER TABLE edc_transfer_process ALTER COLUMN transferprocess_properties SET DEFAULT '{}';



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-05-16 17:50 UTC, paullatzelsperger commented
@florianrusch-zf #359 fixes the markdown errors

2023-05-16 18:17 UTC, merged