fix: Rename ingress endpoint from ids to protocol
eclipse-tractusx/tractusx-edc pull request #358
Opened 2023-05-16 15:53 UTC by tuncaytunc-zf

## WHAT

Rename ingress endpoint from `ids` to `protocol`

## WHY

The ingress endpoint was pointing to wrong endpoint

## FURTHER NOTES

Closes #348

2023-05-16 16:36 UTC, paullatzelsperger approved these changes

2023-05-16 16:37 UTC, paullatzelsperger commented
@tuncaytunc-zf did you check the other charts as well? `-azure-vault` an `-memory`?

2023-05-17 05:14 UTC, paullatzelsperger requested changes
please also change this in `charts/tractusx-connector-memory/values.yaml`

2023-05-17 06:47 UTC, tuncaytunc-zf commented
> please also change this in `charts/tractusx-connector-memory/values.yaml`

In `tractus-xconnector-memory` at least the ingress was matching with endpoint but of course they should be consistent therefore I have renamed it.

2023-05-17 07:31 UTC, merged